##Codebook
## Idea on how to create Codebook from Stackoverflow
# http://stackoverflow.com/questions/5333280/what-is-the-official-way-of-creating-structuring-maintaining-and-updating-da






codebook.ex_data<-data.frame(variable.name=c(names(mergedEx)), 
    label=c("Activity Code",
            "Activity Description", 
            "Subject",
            "Mean of X of Time of Body  Acceleration",
            "Mean of Y of Time of Body  Acceleration",
            "Mean of Z of Time of Body  Acceleration",
            "St.Dev of X of Time of Body  Acceleration",
            "St.Dev of Y of Time of Body  Acceleration",
            "St.Dev of Z of Time of Body  Acceleration",
            "Mean of X of Time of Gravity Acceleration",
            "Mean of Y of Time of Gravity Acceleration",
            "Mean of Z of Time of Gravity Acceleration",
            "St.Dev of X of Time of Gravity Acceleration",
            "St.Dev of Y of Time of Gravity Acceleration",
            "St.Dev of Z of Time of Gravity Acceleration",
            "Mean of X of Time of Body Jerk Acceleration",
            "Mean of Y of Time of Body Jerk Acceleration",
            "Mean of Z of Time of Body Jerk Acceleration",
            "St.Dev of X of Time of Body Jerk Acceleration",
            "St.Dev of Y of Time of Body Jerk Acceleration",
            "St.Dev of Z of Time of Body Jerk Acceleration",
            "Mean of X of Time of Body Gyro  Acceleration",
            "Mean of Y of Time of Body Gyro  Acceleration",
            "Mean of Z of Time of Body Gyro  Acceleration",
            "St.Dev of X of Time of Body Gyro  Acceleration",
            "St.Dev of Y of Time of Body Gyro  Acceleration",
            "St.Dev of Z of Time of Body Gyro  Acceleration",
            "Mean of X of Time of Body Gyro Jerk Acceleration",
            "Mean of Y of Time of Body Gyro Jerk Acceleration",
            "Mean of Z of Time of Body Gyro Jerk Acceleration",
            "St.Dev of X of Time of Body Gyro Jerk Acceleration",
            "St.Dev of Y of Time of Body Gyro Jerk Acceleration",
            "St.Dev of Z of Time of Body Gyro Jerk Acceleration",
            "Mean of X of Frequency of Body  Acceleration",
            "Mean of Y of Frequency of Body  Acceleration",
            "Mean of Z of Frequency of Body  Acceleration",
            "St.Dev of X of Frequency of Body  Acceleration",
            "St.Dev of Y of Frequency of Body  Acceleration",
            "St.Dev of Z of Frequency of Body  Acceleration",
            "Mean of X of Frequency of Body Jerk Acceleration",
            "Mean of Y of Frequency of Body Jerk Acceleration",
            "Mean of Z of Frequency of Body Jerk Acceleration",
            "St.Dev of X of Frequency of Body Jerk Acceleration",
            "St.Dev of Y of Frequency of Body Jerk Acceleration",
            "St.Dev of Z of Frequency of Body Jerk Acceleration",
            "Mean of X of Frequency of Body Gyro  Acceleration",
            "Mean of Y of Frequency of Body Gyro  Acceleration",
            "Mean of Z of Frequency of Body Gyro  Acceleration",
            "St.Dev of X of Frequency of Body Gyro  Acceleration",
            "St.Dev of Y of Frequency of Body Gyro  Acceleration",
            "St.Dev of Z of Frequency of Body Gyro  Acceleration"),
            source=rep("Anguita,  Ghio,  Oneto,  Parra and Reyes-Ortiz. (2012)", length(mergedEx)),
            source_media=rep("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"),
            filename=rep("mergedEx",length(mergedEx)),
            notes=rep("Howework for Coursera", length(mergedEx))
)

codebook.tex_data<-data.frame(variable.name=c(names(tidy_ex)), 
                             label=c("Activity Code",
                                     "Activity Description", 
                                     "Subject",
                                     "Mean of X of Time of Body  Acceleration",
                                     "Mean of Y of Time of Body  Acceleration",
                                     "Mean of Z of Time of Body  Acceleration",
                                     "St.Dev of X of Time of Body  Acceleration",
                                     "St.Dev of Y of Time of Body  Acceleration",
                                     "St.Dev of Z of Time of Body  Acceleration",
                                     "Mean of X of Time of Gravity Acceleration",
                                     "Mean of Y of Time of Gravity Acceleration",
                                     "Mean of Z of Time of Gravity Acceleration",
                                     "St.Dev of X of Time of Gravity Acceleration",
                                     "St.Dev of Y of Time of Gravity Acceleration",
                                     "St.Dev of Z of Time of Gravity Acceleration",
                                     "Mean of X of Time of Body Jerk Acceleration",
                                     "Mean of Y of Time of Body Jerk Acceleration",
                                     "Mean of Z of Time of Body Jerk Acceleration",
                                     "St.Dev of X of Time of Body Jerk Acceleration",
                                     "St.Dev of Y of Time of Body Jerk Acceleration",
                                     "St.Dev of Z of Time of Body Jerk Acceleration",
                                     "Mean of X of Time of Body Gyro  Acceleration",
                                     "Mean of Y of Time of Body Gyro  Acceleration",
                                     "Mean of Z of Time of Body Gyro  Acceleration",
                                     "St.Dev of X of Time of Body Gyro  Acceleration",
                                     "St.Dev of Y of Time of Body Gyro  Acceleration",
                                     "St.Dev of Z of Time of Body Gyro  Acceleration",
                                     "Mean of X of Time of Body Gyro Jerk Acceleration",
                                     "Mean of Y of Time of Body Gyro Jerk Acceleration",
                                     "Mean of Z of Time of Body Gyro Jerk Acceleration",
                                     "St.Dev of X of Time of Body Gyro Jerk Acceleration",
                                     "St.Dev of Y of Time of Body Gyro Jerk Acceleration",
                                     "St.Dev of Z of Time of Body Gyro Jerk Acceleration",
                                     "Mean of X of Frequency of Body  Acceleration",
                                     "Mean of Y of Frequency of Body  Acceleration",
                                     "Mean of Z of Frequency of Body  Acceleration",
                                     "St.Dev of X of Frequency of Body  Acceleration",
                                     "St.Dev of Y of Frequency of Body  Acceleration",
                                     "St.Dev of Z of Frequency of Body  Acceleration",
                                     "Mean of X of Frequency of Body Jerk Acceleration",
                                     "Mean of Y of Frequency of Body Jerk Acceleration",
                                     "Mean of Z of Frequency of Body Jerk Acceleration",
                                     "St.Dev of X of Frequency of Body Jerk Acceleration",
                                     "St.Dev of Y of Frequency of Body Jerk Acceleration",
                                     "St.Dev of Z of Frequency of Body Jerk Acceleration",
                                     "Mean of X of Frequency of Body Gyro  Acceleration",
                                     "Mean of Y of Frequency of Body Gyro  Acceleration",
                                     "Mean of Z of Frequency of Body Gyro  Acceleration",
                                     "St.Dev of X of Frequency of Body Gyro  Acceleration",
                                     "St.Dev of Y of Frequency of Body Gyro  Acceleration",
                                     "St.Dev of Z of Frequency of Body Gyro  Acceleration"),
                             source=rep("Anguita,  Ghio,  Oneto,  Parra and Reyes-Ortiz. (2012)", length(mergedEx)),
                             source_media=rep("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"),
                             filename=rep("mergedEx",length(mergedEx)),
                             notes=rep("Howework for Coursera", length(mergedEx))
)

                    )